/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ProgrammingPC' at '12/8/16 7:06 PM' with Gradle 2.9
 *
 * @author ProgrammingPC, @date 12/8/16 7:06 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
